kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-role
  namespace: argocd
rules:
  - apiGroups: ["", "batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["list", "watch", "get", "create",  "update", "patch"]